// This file is generated by scripts/update-holidays.mjs
// Generated at: 2026-04-14T09:20:53.052Z

export const HOLIDAY_DATA = Object.freeze({
  "2021": [
    {
      "dateKey": "2021-05-12",
      "label": "Ramazan Bayramı Arefesi",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=141"
    },
    {
      "dateKey": "2021-05-13",
      "label": "Ramazan Bayramı (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=141"
    },
    {
      "dateKey": "2021-05-14",
      "label": "Ramazan Bayramı (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=141"
    },
    {
      "dateKey": "2021-05-15",
      "label": "Ramazan Bayramı (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=141"
    },
    {
      "dateKey": "2021-07-19",
      "label": "Kurban Bayramı Arefesi",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=141"
    },
    {
      "dateKey": "2021-07-20",
      "label": "Kurban Bayramı (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=141"
    },
    {
      "dateKey": "2021-07-21",
      "label": "Kurban Bayramı (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=141"
    },
    {
      "dateKey": "2021-07-22",
      "label": "Kurban Bayramı (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=141"
    },
    {
      "dateKey": "2021-07-23",
      "label": "Kurban Bayramı (4. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=141"
    }
  ],
  "2022": [
    {
      "dateKey": "2022-05-01",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2022"
    },
    {
      "dateKey": "2022-05-02",
      "label": "RAMAZAN BAYRAMI (1.Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2022"
    },
    {
      "dateKey": "2022-05-03",
      "label": "RAMAZAN BAYRAMI (2.Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2022"
    },
    {
      "dateKey": "2022-05-04",
      "label": "RAMAZAN BAYRAMI (3.Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2022"
    },
    {
      "dateKey": "2022-07-08",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2022"
    },
    {
      "dateKey": "2022-07-09",
      "label": "KURBAN BAYRAMI (1.Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2022"
    },
    {
      "dateKey": "2022-07-10",
      "label": "KURBAN BAYRAMI (2.Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2022"
    },
    {
      "dateKey": "2022-07-11",
      "label": "KURBAN BAYRAMI (3.Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2022"
    },
    {
      "dateKey": "2022-07-12",
      "label": "KURBAN BAYRAMI (4.Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2022"
    }
  ],
  "2023": [
    {
      "dateKey": "2023-04-20",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2023"
    },
    {
      "dateKey": "2023-04-21",
      "label": "RAMAZAN BAYRAMI (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2023"
    },
    {
      "dateKey": "2023-04-22",
      "label": "RAMAZAN BAYRAMI (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2023"
    },
    {
      "dateKey": "2023-04-23",
      "label": "RAMAZAN BAYRAMI (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2023"
    },
    {
      "dateKey": "2023-06-27",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2023"
    },
    {
      "dateKey": "2023-06-28",
      "label": "KURBAN BAYRAMI (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2023"
    },
    {
      "dateKey": "2023-06-29",
      "label": "KURBAN BAYRAMI (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2023"
    },
    {
      "dateKey": "2023-06-30",
      "label": "KURBAN BAYRAMI (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2023"
    },
    {
      "dateKey": "2023-07-01",
      "label": "KURBAN BAYRAMI (4. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2023"
    }
  ],
  "2024": [
    {
      "dateKey": "2024-04-09",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2024"
    },
    {
      "dateKey": "2024-04-10",
      "label": "RAMAZAN BAYRAMI (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2024"
    },
    {
      "dateKey": "2024-04-11",
      "label": "RAMAZAN BAYRAMI (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2024"
    },
    {
      "dateKey": "2024-04-12",
      "label": "RAMAZAN BAYRAMI (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2024"
    },
    {
      "dateKey": "2024-06-15",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2024"
    },
    {
      "dateKey": "2024-06-16",
      "label": "KURBAN BAYRAMI (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2024"
    },
    {
      "dateKey": "2024-06-17",
      "label": "KURBAN BAYRAMI (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2024"
    },
    {
      "dateKey": "2024-06-18",
      "label": "KURBAN BAYRAMI (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2024"
    },
    {
      "dateKey": "2024-06-19",
      "label": "KURBAN BAYRAMI (4. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2024"
    }
  ],
  "2025": [
    {
      "dateKey": "2025-03-29",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=152"
    },
    {
      "dateKey": "2025-03-30",
      "label": "RAMAZAN BAYRAMI (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=152"
    },
    {
      "dateKey": "2025-03-31",
      "label": "RAMAZAN BAYRAMI (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=152"
    },
    {
      "dateKey": "2025-04-01",
      "label": "RAMAZAN BAYRAMI (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=152"
    },
    {
      "dateKey": "2025-06-05",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=152"
    },
    {
      "dateKey": "2025-06-06",
      "label": "KURBAN BAYRAMI (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=152"
    },
    {
      "dateKey": "2025-06-07",
      "label": "KURBAN BAYRAMI (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=152"
    },
    {
      "dateKey": "2025-06-08",
      "label": "KURBAN BAYRAMI (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=152"
    },
    {
      "dateKey": "2025-06-09",
      "label": "KURBAN BAYRAMI (4. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=152"
    }
  ],
  "2026": [
    {
      "dateKey": "2026-03-19",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=153"
    },
    {
      "dateKey": "2026-03-20",
      "label": "RAMAZAN BAYRAMI (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=153"
    },
    {
      "dateKey": "2026-03-21",
      "label": "RAMAZAN BAYRAMI (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=153"
    },
    {
      "dateKey": "2026-03-22",
      "label": "RAMAZAN BAYRAMI (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=153"
    },
    {
      "dateKey": "2026-05-26",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=153"
    },
    {
      "dateKey": "2026-05-27",
      "label": "KURBAN BAYRAMI (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=153"
    },
    {
      "dateKey": "2026-05-28",
      "label": "KURBAN BAYRAMI (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=153"
    },
    {
      "dateKey": "2026-05-29",
      "label": "KURBAN BAYRAMI (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=153"
    },
    {
      "dateKey": "2026-05-30",
      "label": "KURBAN BAYRAMI (4. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=153"
    }
  ],
  "2027": [
    {
      "dateKey": "2027-03-08",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=154"
    },
    {
      "dateKey": "2027-03-09",
      "label": "RAMAZAN BAYRAMI (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=154"
    },
    {
      "dateKey": "2027-03-10",
      "label": "RAMAZAN BAYRAMI (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=154"
    },
    {
      "dateKey": "2027-03-11",
      "label": "RAMAZAN BAYRAMI (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=154"
    },
    {
      "dateKey": "2027-05-15",
      "label": "AREFE",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=154"
    },
    {
      "dateKey": "2027-05-16",
      "label": "KURBAN BAYRAMI (1. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=154"
    },
    {
      "dateKey": "2027-05-17",
      "label": "KURBAN BAYRAMI (2. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=154"
    },
    {
      "dateKey": "2027-05-18",
      "label": "KURBAN BAYRAMI (3. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=154"
    },
    {
      "dateKey": "2027-05-19",
      "label": "KURBAN BAYRAMI (4. Gün)",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=154"
    }
  ],
  "2028": [
    {
      "dateKey": "2028-02-25",
      "label": "RAMAZAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=185"
    },
    {
      "dateKey": "2028-02-26",
      "label": "RAMAZAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=185"
    },
    {
      "dateKey": "2028-02-27",
      "label": "RAMAZAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=185"
    },
    {
      "dateKey": "2028-02-28",
      "label": "RAMAZAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=185"
    },
    {
      "dateKey": "2028-05-04",
      "label": "KURBAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=185"
    },
    {
      "dateKey": "2028-05-05",
      "label": "KURBAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=185"
    },
    {
      "dateKey": "2028-05-06",
      "label": "KURBAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=185"
    },
    {
      "dateKey": "2028-05-07",
      "label": "KURBAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=185"
    },
    {
      "dateKey": "2028-05-08",
      "label": "KURBAN BAYRAMI 4. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=185"
    }
  ],
  "2029": [
    {
      "dateKey": "2029-02-13",
      "label": "RAMAZAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=186"
    },
    {
      "dateKey": "2029-02-14",
      "label": "RAMAZAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=186"
    },
    {
      "dateKey": "2029-02-15",
      "label": "RAMAZAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=186"
    },
    {
      "dateKey": "2029-02-16",
      "label": "RAMAZAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=186"
    },
    {
      "dateKey": "2029-04-23",
      "label": "KURBAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=186"
    },
    {
      "dateKey": "2029-04-24",
      "label": "KURBAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=186"
    },
    {
      "dateKey": "2029-04-25",
      "label": "KURBAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=186"
    },
    {
      "dateKey": "2029-04-26",
      "label": "KURBAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=186"
    },
    {
      "dateKey": "2029-04-27",
      "label": "KURBAN BAYRAMI 4. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=186"
    }
  ],
  "2030": [
    {
      "dateKey": "2030-02-03",
      "label": "RAMAZAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=187"
    },
    {
      "dateKey": "2030-02-04",
      "label": "RAMAZAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=187"
    },
    {
      "dateKey": "2030-02-05",
      "label": "RAMAZAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=187"
    },
    {
      "dateKey": "2030-02-06",
      "label": "RAMAZAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=187"
    },
    {
      "dateKey": "2030-04-12",
      "label": "KURBAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=187"
    },
    {
      "dateKey": "2030-04-13",
      "label": "KURBAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=187"
    },
    {
      "dateKey": "2030-04-14",
      "label": "KURBAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=187"
    },
    {
      "dateKey": "2030-04-15",
      "label": "KURBAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=187"
    },
    {
      "dateKey": "2030-04-16",
      "label": "KURBAN BAYRAMI 4. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=187"
    }
  ],
  "2031": [
    {
      "dateKey": "2031-01-23",
      "label": "RAMAZAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=188"
    },
    {
      "dateKey": "2031-01-24",
      "label": "RAMAZAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=188"
    },
    {
      "dateKey": "2031-01-25",
      "label": "RAMAZAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=188"
    },
    {
      "dateKey": "2031-01-26",
      "label": "RAMAZAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=188"
    },
    {
      "dateKey": "2031-04-01",
      "label": "KURBAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=188"
    },
    {
      "dateKey": "2031-04-02",
      "label": "KURBAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=188"
    },
    {
      "dateKey": "2031-04-03",
      "label": "KURBAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=188"
    },
    {
      "dateKey": "2031-04-04",
      "label": "KURBAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=188"
    },
    {
      "dateKey": "2031-04-05",
      "label": "KURBAN BAYRAMI 4. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=188"
    }
  ],
  "2032": [
    {
      "dateKey": "2032-01-13",
      "label": "RAMAZAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=189"
    },
    {
      "dateKey": "2032-01-14",
      "label": "RAMAZAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=189"
    },
    {
      "dateKey": "2032-01-15",
      "label": "RAMAZAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=189"
    },
    {
      "dateKey": "2032-01-16",
      "label": "RAMAZAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=189"
    },
    {
      "dateKey": "2032-03-21",
      "label": "KURBAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=189"
    },
    {
      "dateKey": "2032-03-22",
      "label": "KURBAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=189"
    },
    {
      "dateKey": "2032-03-23",
      "label": "KURBAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=189"
    },
    {
      "dateKey": "2032-03-24",
      "label": "KURBAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=189"
    },
    {
      "dateKey": "2032-03-25",
      "label": "KURBAN BAYRAMI 4. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=189"
    }
  ],
  "2033": [
    {
      "dateKey": "2033-01-01",
      "label": "RAMAZAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-01-02",
      "label": "RAMAZAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-01-03",
      "label": "RAMAZAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-01-04",
      "label": "RAMAZAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-03-10",
      "label": "KURBAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-03-11",
      "label": "KURBAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-03-12",
      "label": "KURBAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-03-13",
      "label": "KURBAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-03-14",
      "label": "KURBAN BAYRAMI 4. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-12-22",
      "label": "RAMAZAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-12-23",
      "label": "RAMAZAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-12-24",
      "label": "RAMAZAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    },
    {
      "dateKey": "2033-12-25",
      "label": "RAMAZAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190"
    }
  ],
  "2034": [
    {
      "dateKey": "2034-02-28",
      "label": "KURBAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=191"
    },
    {
      "dateKey": "2034-03-01",
      "label": "KURBAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=191"
    },
    {
      "dateKey": "2034-03-02",
      "label": "KURBAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=191"
    },
    {
      "dateKey": "2034-03-03",
      "label": "KURBAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=191"
    },
    {
      "dateKey": "2034-03-04",
      "label": "KURBAN BAYRAMI 4. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=191"
    },
    {
      "dateKey": "2034-12-11",
      "label": "RAMAZAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=191"
    },
    {
      "dateKey": "2034-12-12",
      "label": "RAMAZAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=191"
    },
    {
      "dateKey": "2034-12-13",
      "label": "RAMAZAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=191"
    },
    {
      "dateKey": "2034-12-14",
      "label": "RAMAZAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=191"
    }
  ],
  "2035": [
    {
      "dateKey": "2035-02-17",
      "label": "KURBAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=192"
    },
    {
      "dateKey": "2035-02-18",
      "label": "KURBAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=192"
    },
    {
      "dateKey": "2035-02-19",
      "label": "KURBAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=192"
    },
    {
      "dateKey": "2035-02-20",
      "label": "KURBAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=192"
    },
    {
      "dateKey": "2035-02-21",
      "label": "KURBAN BAYRAMI 4. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=192"
    },
    {
      "dateKey": "2035-11-30",
      "label": "RAMAZAN BAY. AREFESİ",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=192"
    },
    {
      "dateKey": "2035-12-01",
      "label": "RAMAZAN BAYRAMI 1. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=192"
    },
    {
      "dateKey": "2035-12-02",
      "label": "RAMAZAN BAYRAMI 2. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=192"
    },
    {
      "dateKey": "2035-12-03",
      "label": "RAMAZAN BAYRAMI 3. Gün",
      "category": "religious",
      "source": "diyanet",
      "sourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=192"
    }
  ]
})

export const HOLIDAY_SOURCES = Object.freeze({
  "diyanet": {
    "manualYears": [
      2021
    ],
    "fetchedYears": [
      2022,
      2023,
      2024,
      2025,
      2026,
      2027,
      2028,
      2029,
      2030,
      2031,
      2032,
      2033,
      2034,
      2035
    ],
    "historicalSourceUrl": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=141",
    "yearlySourceUrls": {
      "2022": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2022",
      "2023": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2023",
      "2024": "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2024",
      "2025": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=152",
      "2026": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=153",
      "2027": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=154",
      "2028": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=185",
      "2029": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=186",
      "2030": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=187",
      "2031": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=188",
      "2032": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=189",
      "2033": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=190",
      "2034": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=191",
      "2035": "https://vakithesaplama.diyanet.gov.tr/icerik.php?icerik=192"
    }
  }
})

export function getHolidayEntries(year) {
  return HOLIDAY_DATA[String(year)] ?? []
}

export function getHolidaySet(year) {
  return new Set(getHolidayEntries(year).map((entry) => entry.dateKey))
}

export function getHolidayDetails(dateKey) {
  const year = String(dateKey ?? '').slice(0, 4)
  return (HOLIDAY_DATA[year] ?? []).filter((entry) => entry.dateKey === dateKey)
}
